services:
  - type: web
    name: my-vaadin-app
    env: docker
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render/java
      - key: PATH
        value: /opt/render/project/.render/java/bin:$PATH
      - key: MAVEN_OPTS
        value: -Dmaven.repo.local=/opt/render/cache/.m2
